### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by jibanes** [aplteam/Cookbook_Make#6]
it's expecting .Cookbook, while dyalog-cookbook holds a .cookbook (notice the case mismatch).

upon invokation (on linux, dyalog 16/amd64):

SYNTAX ERROR
GetListOfAllChapters[10] list2←{' '@(⍸'-'=⍵)⊣⍵}¨list2

list2 contains:
 Introduction  Packaging  Handling-errors  Windows-Services  Structure  Appendix-04_Development-environment  Make  Acre  Creating-SetUp.exe  Appendix-02_User-commands  Appendix-05_Special-characters  Logging   Regular-Expressions  Documentation  Appendix-03_aplcores-&-WS-integrity  Testing  GUI  Git  Scheduled-Tasks  Configuration  Debugging-EXEs  Appendix-01_Windows-environment-vars  Providing-help  Windows-Event-Log  Windows-Registry

**Comment by aplteam** [comment]
Corrected.
